FROM python:3.12-slim

ARG HTTP_PROXY
ARG HTTPS_PROXY
# Set proxy environment variables
ENV HTTP_PROXY=${HTTP_PROXY} \
    HTTPS_PROXY=${HTTPS_PROXY} \
    http_proxy=${HTTP_PROXY} \
    https_proxy=${HTTPS_PROXY}
# Install system libraries for OpenCV and GStreamer
RUN apt-get update && apt-get install -y --no-install-recommends \
    libsm6 libxext6 libgl1 gstreamer1.0-libav \
    gstreamer1.0-tools \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    python3-opencv \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app
# Install Python dependencies
RUN pip install --no-cache-dir opencv-python
# Copy script into container
COPY src/loop_video.py .
COPY config/sample-videos /sample-videos
# Entrypoint: Run OpenCV script → then compress using GStreamer
CMD ["sh", "-c", "\
  if [ -f /sample-videos/qsr-usecase.mp4 ]; then \
    python loop_video.py && \
    mkdir -p /sample-videos/compressed-video && \
    gst-launch-1.0 filesrc location=/sample-videos/increased-video/qsr-usecase.mp4 ! decodebin ! x264enc bitrate=800 ! mp4mux ! filesink location=/sample-videos/compressed-video/qsr-usecase.mp4 && \
    cp /sample-videos/compressed-video/qsr-usecase.mp4 /sample-videos/qsr-usecase.mp4; \
  else \
    echo \"No qsr video file found\"; \
  fi"]


